package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.33

import (
	"context"
	"fmt"
	"time"

	model "github.com/LabbJoil/Chat/Models"
)

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, senderID string, idConversation string, content string) (*model.Message, error) {
	returnMessage, err := r.ServiceChat.GenerateMessage(senderID, idConversation, content)
	if err != nil {
		return nil, err
	}
	return returnMessage, nil
}

// DeleteChatByUser is the resolver for the deleteChatByUser field.
func (r *mutationResolver) DeleteChatByUser(ctx context.Context, userID string) (bool, error) {
	err := r.ServiceChat.DeleteChatByUser(userID)
	if err != nil {
		return false, err
	}
	return true, nil
}

// DeleteMessage is the resolver for the deleteMessage field.
func (r *mutationResolver) DeleteMessage(ctx context.Context, messageID string) (bool, error) {
	err := r.ServiceChat.DeleteMessageByMessage(messageID)
	if err != nil {
		return false, err
	}
	return true, nil
}

// AllMessages is the resolver for the allMessages field.
func (r *queryResolver) AllMessages(ctx context.Context, fromUserID string, queryUserID string, count string, afterMeesageID string) ([]*model.Message, error) {
	allMessageFromUser, err := r.ServiceChat.GetAllMessagesByUserId(fromUserID, queryUserID, afterMeesageID, count)
	if err != nil {
		return nil, err
	}
	return allMessageFromUser, nil
}

// AllChats is the resolver for the allChats field.
func (r *queryResolver) AllChats(ctx context.Context, userID string) ([]*model.Chat, error) {
	allChatsUser, err := r.ServiceChat.GetUserChat(userID)
	if err != nil {
		return nil, err
	}
	return allChatsUser, nil
}

// MessageSent is the resolver for the messageSent field.
func (r *subscriptionResolver) MessageSent(ctx context.Context, userID string) (<-chan *model.Message, error) {
	messageChan := make(chan *model.Message)

	go func() {

		for {
			select {
			case <-ctx.Done():
				return
			default:
				fmt.Println("...")
				newMessages, err := r.ServiceChat.GetMessagesByUserId(userID)
				if err != nil {
					time.Sleep(time.Second * 5)
					continue
				}
				for _, message := range *newMessages {
					messageChan <- &message
				}
				time.Sleep(time.Second)
			}
		}
	}()

	return messageChan, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
